### ISSUE TITLE
Visual artefacting/clipping

### ISSUE THREAD

**Issue by fran-man** [bitbrain/fishmonger#13]
Don't really know anything about graphics but there seemed to be what looked like visual tearing occasionally, it seemed to be when casting the lure, I noticed some very subtle black lines flicking on the screen...almost like two panels rendered with a pixel inbetween.

It was so quick it was impossible to get a screenshot! Sorry :(

**Comment by bitbrain** [comment]
Hey,

thanks for reporting. This is a known issue and [I will fix this with this approach](https://www.badlogicgames.com/wordpress/?p=1403). We simply didn't had the time to investigate that further.

**Comment by bitbrain** [comment]
This issue is now been resolved with the newest build I am just about to release. The issue of texture clipping is quite well known and there are different techniques how to fix this. I went for the quite simple approach:

1. export tileset with 2px padding and 2px margin between the tiles
2. copy the edges of each tile into the empty space ("texture bleeding")

This solves the issue. However, I applied the bleeding effect manually. Ideally, this should be done by [TexturePacker](https://github.com/libgdx/libgdx/wiki/Texture-packer) as part of the build.
